// <auto-generated />
using CodeFirstPractice.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CodeFirstPractice.Migrations
{
    [DbContext(typeof(ShelvesCodeFirstContext))]
    [Migration("20200918001126_ShelfSeedData")]
    partial class ShelfSeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CodeFirstPractice.Models.CodeFirstShelf", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("varchar(50)")
                        .HasAnnotation("MySql:CharSet", "utf8mb4")
                        .HasAnnotation("MySql:Collation", "utf8mb4_general_ci");

                    b.HasKey("ID");

                    b.ToTable("Shelves");

                    b.HasData(
                        new
                        {
                            ID = 3,
                            Name = "Book Shelf"
                        },
                        new
                        {
                            ID = 4,
                            Name = "Pen Shelf"
                        },
                        new
                        {
                            ID = 5,
                            Name = "Chair Shelf"
                        },
                        new
                        {
                            ID = 6,
                            Name = "Boxes Shelf"
                        },
                        new
                        {
                            ID = 7,
                            Name = "Cards Shelf"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
